language: python

python:
  - 3.7
  - 3.6
  - 3.8

before_install: pip install pytest pytest-cov codecov

install: pip install .

script:
  - pytest -v --cov-config=.coveragerc --cov=./peridynamics

after_success:
  - codecov

jobs:
  include:
    - name: Lint
      before-install: pip install flake8 flake8-docstrings
      install:
      script: flake8
      after_success:
    - name: Build documentation
      before-install: pip install sphinx
      script: sphinx-build -W -b html docs build
      after_success:
