language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install .
  - pip install flake8 pytest sphinx

script:
  - flake8
  - pytest -v

jobs:
  include:
    - python: 3.8
      script: sphinx-build docs build
